### ISSUE TITLE
can not run 

### ISSUE THREAD

**Issue by Wang-Alan** [gaoyu19920914/miaSimShiny#1]
When I run the command 'miaSimShiny::run_app()', a lot of error occur. I list them below:

Listening on http://127.0.0.1:5828
Warning: Error in randomE: unused arguments (names_species = names_species_crm(), names_resources = names_resources_crm(), mean_consumption = as.integer(mean_consumption_crm() * n_resources_crm()), mean_production = as.integer(mean_production_crm() * n_resources_crm()))
  47: observe
  46: <observer>
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning: Error in t.default: argument is not a matrix
  174: t.default
  171: makeHeatmap
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$CRMPlotE
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in rdirichlet: could not find function "rdirichlet"
  84: <reactive>
  68: resources_dist_crm
  66: <reactive>
  50: resources_crm
  47: observe
  46: <observer>
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning: Error in rdirichlet: could not find function "rdirichlet"
  193: <Anonymous>
  192: stop
  191: resources_crm
  189: <reactive>
  187: .func
  184: contextFunc
  183: env$runWith
  176: ctx$run
  175: self$.updateValue
  173: runCRM
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$CRMSpecies
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in rdirichlet: could not find function "rdirichlet"
  175: <Anonymous>
  174: stop
  173: runCRM
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$CRMResources
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in rdirichlet: could not find function "rdirichlet"
  175: <Anonymous>
  174: stop
  173: runCRM
  170: renderPlot
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$CRMVolume
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in randomA: unused arguments (names_species = names_species_glv(), diagonal = diagonal_glv(), scale_off_diagonal = scale_glv(), mutualism = mutualism_glv(), commensalism = commensalism_glv(), parasitism = parasitism_glv(), amensalism = amensalism_glv(), competition = competition_glv(), interactions = interactions_glv())
  47: observe
  46: <observer>
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>

**Comment by gaoyu19920914** [comment]
Hi,

Thanks for your feedback.

The problem may be caused by different versions of dependencies.
Can you try installing miaSim via `devtools::install_github("microbiome/miaSim")` to see whether this issue persists? 

Thanks again for your help!

**Comment by Wang-Alan** [comment]
Thank you! The issue has been solved.
